### ISSUE TITLE
Background long running scripts

### ISSUE THREAD

**Issue by roostercactus** [fboender/scriptform#6]
Hi, I've read over the docs and tried several things but I can't seem to get this to work.  My example is a script that takes about 6-8 hours to complete.  So I don't want to hold the web page open for that long.  I'd like to just allow the person to run the script and have it background and log to a local log on the server.

Here's what I've tried that doesn't seem to work:  

"script": "/root/sbin/httpd_memory_usage.sh &",
"script": "/root/sbin/httpd_memory_usage.sh > /tmp/somelog",
"script": "/root/sbin/httpd_memory_usage.sh > /tmp/somelog &",
"script": "/root/sbin/httpd_memory_usage.sh" > /tmp/somelog,

I've also tried to add escapes inside the quotes but that didn't help.  I've also tried changing the output to raw.  Is there a way to do this?  Maybe I'm just not seeing an obvious solution.  Thanks for the great software!

**Comment by fboender** [comment]
Hi!

You'll have to write a wrapper script that calls another script with & at the end. Scriptform itself doesn't execute commands in a shell, to prevent misuse. So you can't have special things such as & in the "script" value.

Hope that helps! If not, please let me know!
